import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {ROUTE_REGISTRY,getRoute} from './navigation/context-horizon/route-registry.mjs';
const gpu=await readFile(new URL('./space-lens-gpu.js',import.meta.url),'utf8');
const master=await readFile(new URL('./space-lens-master.js',import.meta.url),'utf8');
const home=await readFile(new URL('./index.html',import.meta.url),'utf8');
const play=await readFile(new URL('./play/index.html',import.meta.url),'utf8');
const simple=await readFile(new URL('./play/mmo/simple/index.html',import.meta.url),'utf8');
const research=await readFile(new URL('./research/projects/index.html',import.meta.url),'utf8');
const history=await readFile(new URL('./history/index.html',import.meta.url),'utf8');
const horizon=await readFile(new URL('./navigation/context-horizon/index.html',import.meta.url),'utf8');
const horizonCss=await readFile(new URL('./navigation/context-horizon/context-horizon.css',import.meta.url),'utf8');
const seeds=JSON.parse(await readFile(new URL('./navigation/context-horizon/preservation-seeds.json',import.meta.url),'utf8'));
const externalPublic=JSON.parse(await readFile(new URL('./navigation/context-horizon/external-public-sources.json',import.meta.url),'utf8'));
const inventory=JSON.parse(await readFile(new URL('./navigation/context-horizon/WORK_INVENTORY.json',import.meta.url),'utf8'));
const gameMap=JSON.parse(await readFile(new URL('./play/mmo/web-links.json',import.meta.url),'utf8'));
assert.match(gpu,/XYZ geometry \+ perspective projection/);
assert.match(gpu,/WebGPU -> WebGL2 -> WebGL -> existing Canvas2D/);
assert.match(gpu,/primitive:\{topology:'point-list'\}/);
assert.match(gpu,/gl\.drawArrays\(gl\.POINTS,0,COUNT\)/);
assert.match(gpu,/geometry:'xyz-perspective'/);
assert.doesNotMatch(play,/fuzzball-hidden/);
assert.doesNotMatch(home,/href=["'][^"']*fuzzball-hidden/i);
assert.ok(!ROUTE_REGISTRY.routes.some(r=>/fuzzball-hidden/.test(r.href)),'unlisted Fuzzball must not become a public Context Horizon route');
assert.ok(inventory.works.some(w=>w.id==='fuzzball-hidden-alpha'),'unlisted Fuzzball still belongs in preservation inventory');
assert.match(history,/perspective:1200px/);
assert.match(history,/prefers-reduced-motion:reduce/);
assert.match(history,/forced-colors:active/);
assert.match(history,/Context Horizon/);
assert.match(research,/Records retain their findings, failures, evidence boundaries, and unresolved questions; this page is navigation, not a replacement for them\./);
assert.match(research,/Context Horizon/);
assert.doesNotMatch(research,/owned by Red Wilds|game authority|game evidence/i);
assert.match(play,/href="\.\/mmo\/simple\/"/,'Play Hub must point primary MMO navigation to Simple MMO');
assert.match(play,/Context Horizon/);
assert.match(simple,/Context Horizon/);
assert.match(master,/navigation\/context-horizon\/page-adapter\.mjs/,'Space Lens must load Context Horizon without replacing its existing center');
assert.match(horizon,/POETRY != GAME_CONTENT/);
assert.match(horizon,/PHILOSOPHY != GAME_CONTENT/);
assert.match(horizon,/RELATION != MERGE/);
assert.match(horizonCss,/prefers-reduced-motion:reduce/);
assert.match(horizonCss,/forced-colors:active/);
assert.equal(getRoute('research-projects').ownerDomain,'research');
assert.equal(getRoute('research-projects').epistemicRole,'preserved-project-index');
assert.equal(getRoute('mmo-simple').ownerDomain,'game');
assert.equal(ROUTE_REGISTRY.primaryRoute,'conscience-root');
assert.equal(gameMap.primaryRoute,'mmo-simple');
assert.ok(!gameMap.routes.some(r=>r.id==='research-projects'),'game projection must not absorb research routes');
const ids=new Set(inventory.works.map(w=>w.id));
for(const seed of seeds.works)assert.ok(ids.has(seed.id),`preservation seed dropped: ${seed.id}`);
for(const source of externalPublic.works)assert.ok(ids.has(source.id),`external public work dropped: ${source.id}`);
assert.equal(inventory.works.find(w=>w.id==='poetry-family')?.domain,'poetry');
assert.equal(inventory.works.find(w=>w.id==='philosophy-family')?.domain,'philosophy');
assert.equal(inventory.works.find(w=>w.id==='poetry-family')?.state,'unresolved');
assert.equal(inventory.works.find(w=>w.id==='philosophy-family')?.state,'unresolved');
assert.ok(inventory.works.find(w=>w.id==='dream-to-action')?.sourceLocations.includes('github:redogit/Dream-To-Action'),'external Dream to Action source must resolve');
assert.ok(inventory.works.find(w=>w.id==='human-expression-archive')?.sourceLocations.includes('github:redogit/Other-Projects-/Human Expression Archive/'),'Human Expression Archive source must resolve');
assert.equal(inventory.works.some(w=>w.canonicalName==='DnD'),false,'private repository identity must not appear in public preservation inventory');
console.log(`PASS spatial UI + Context Horizon: GPU fallbacks, accessible depth, ${seeds.works.length} preservation seeds retained, ${externalPublic.works.length} public external works retained, peer domains isolated, hidden-game and private-repository boundaries preserved.`);
